name: Merge to Main

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config user.name "jeon9825"
          git config user.email "jy201735031@gmail.com"

      - name: Fetch all branches
        run: git fetch --all --unshallow

      - name: Merge dev into main
        run: |
          git checkout main
          git pull origin main
          git merge origin/dev  --allow-unrelated-histories || (echo "Merge conflict detected" && exit 1)
          git push origin main

      - name: Handle merge conflict
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            # const issue = await github.rest.issues.create({
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   title: 'Merge Conflict Detected',
            #   body: 'A merge conflict occurred during the automated merge process. Please resolve it manually.',
            #   labels: ['conflict']
            # });
            # console.log(`Created issue with ID: ${issue.data.number}`);
            
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Merge dev into main',
              head: 'dev',
              base: 'main',
              body: 'This pull request merges changes from dev into main.',
              draft: false
            });
            console.log(`Created pull request with ID: ${pullRequest.number}`);

      - name: Send slack when failed
        if: failure()
        uses: ./.github/actions/slack-notify
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send slack if completed
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: success
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}