name: Merge to Main

on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:
  schedule:
    - cron: '0 * * * 1-5'

jobs:
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config user.name "jeon9825"
          git config user.email "jy201735031@gmail.com"

      - name: Fetch all branches
        run: git fetch --all --unshallow

      - name: Merge dev into main
        run: |
          git checkout main
          git pull origin main
          git merge origin/dev --allow-unrelated-histories || (echo "Merge conflict detected" && exit 1)
          git push origin main

      - name: Create Pull Request if needed
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Merge dev into main',
              head: 'dev',
              base: 'main',
              body: 'This pull request merges changes from dev into main.',
              draft: false
            });
            console.log(`Created pull request with ID: ${pullRequest.number}`);
    
  slack-notify:
    runs-on: ubuntu-latest
    needs: merge-to-main
    if: always()  # Ensure this job always runs, regardless of previous job's success or failure
    
    steps:
      - name: Send slack notification
        uses: ./.github/actions/slack-notify
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ needs.merge-to-main.result == 'success' && 'success' || 'failure' }}
